/// <summary>
/// Enumeration of config data names
/// </summary>
public enum ConfigDataName
{
    Ship1MaxShield,
    Ship1LaserCooldown,
    Ship1LaserSpeed,
    Ship1MoveSpeed,
    Ship1LifeAmount,
    Ship1LaserDamage,
    Alien1LaserDamage,
    Alien1LaserCooldownMin,
    Alien1LaserCooldownMax,
    Alien1LaserSpeed,
    Alien1MoveSpeed,
    Alien1MoveDelay,
    Alien1LifeAmount,
    Alien2LaserDamage,
    Alien2LaserCooldownMin,
    Alien2LaserCooldownMax,
    Alien2LaserSpeed,
    Alien2MoveSpeed,
    Alien2MoveDelay,
    Alien2LifeAmount,
    Alien3LaserDamage,
    Alien3LaserCooldownMin,
    Alien3LaserCooldownMax,
    Alien3LaserSpeed,
    Alien3MoveSpeed,
    Alien3MoveDelay,
    Alien3LifeAmount,
    LaserCooldownCost,
    LaserSpeedCost,
    LaserDamageCost,
    MoveSpeedCost,
    LifeAmountCost,
    UpgradeAmount,
    UpgradeCostMultiplier
}
